[features]
seeds = false
skip-lint = false
[programs.localnet]
stream = "5vzwztHZBMekRQDzy9K1PiQrWw3qYYvfwcgapnwcdJLC"

[programs.devnet]
stream = "5vzwztHZBMekRQDzy9K1PiQrWw3qYYvfwcgapnwcdJLC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ppetar/le1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
